# Generated by Django 4.2.16 on 2024-09-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('venue', models.CharField(choices=[('venue1', 'Venue 1'), ('venue2', 'Venue 2'), ('venue3', 'Venue 3'), ('venue4', 'Venue 4'), ('venue5', 'Venue 5')], max_length=10)),
            ],
        ),
    ]
